spring:
  h2.console:
    enabled: true
    path: /h2-console

  r2dbc:
    url: r2dbc:h2:mem:///testdb?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;mode=MySQL;
    username: test
    password:
    pool:
      initial-size: 5
      max-size: 5